### ISSUE TITLE
Checksums are not being calculated

### ISSUE THREAD

**Issue by M1CR0H4CK3R** [kabili207/zora-sharp#1]
Post number 4 at http://www.gamefaqs.com/boards/472313-the-legend-of-zelda-oracle-of-ages/66644736 might help with figuring it out.

I didn't know of any way of bringing this to your attention other than creating a new issue.

**Comment by M1CR0H4CK3R** [comment]
I think one of the 'Unknown' bits is for whether or not Maple has a vacuum cleaner as her vehicle yet. 

Quote from GameFAQs' Maple FAQ (http://www.gamefaqs.com/gbc/198972-the-legend-of-zelda-oracle-of-seasons/faqs/12199):

> ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
> 4. Brooms are so five minutes ago
> _________________________________

> Now, you may be asking, "What does Maple do with all that stuff she stole
> from me?"  You mean you're not wondering that?  Well, mister, perhaps you
> SHOULD be pondering what happens to your lost possessions!  Not everyone is
> is rich enough to not worry about stolen goods!  Anywho, theoretically the
> Rupees you let her "borrow" allows her to upgrade her flying equipment.
> Eventually, in a **"non-Linked Game**," Maple will fly around on her shiny new
> **Vacuum Cleaner** (if you define new as a 1940s Vacuum).  In a password "Linked
> Game," she'll ride around on a brand-spanking new, state-of-the-art Flying
> Saucer!  One wonders why she can't just walk like the rest of us.

The vacuum **does** transfer over to a linked game as well. I confirmed it.

**Comment by kabili207** [comment]
That's good thinking. I've opened a separate issue to deal with the unknown flags since they aren't directly related to the checksum logic.
