### ISSUE TITLE
Blazor WebUI

### ISSUE THREAD

**Issue by friendlyanon** [kabili207/zora-sharp#11]
This library now has a Blazor implementation in a form of an installable PWA.  
You can find said implementation [here](https://github.com/friendlyanon/zoragen-blazor).

**Comment by kabili207** [comment]
Very nice! I'll poke around in the source a bit later, but I like what I'm seeing.

Just a small note: ZoraGen WPF is GPL, not LGPL. Although you only used the images, which belong to Nintendo, so it doesn't really matter anyway.

**Comment by friendlyanon** [comment]
Thank you and apologies, I have corrected the license notice. It was late when I pushed and had too much copy pasting going on to get it done quickly.

**Comment by kabili207** [comment]
I've added a link to the blazor version on the README page with 870498a. I'll follow up with you regarding #10 either tonight or over the weekend.
